version: '3'
services:
  dind:
    image: docker:dind
    privileged: true  # Required for DinD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Share Docker socket 

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_data:/var/jenkins_home
    ports:
      - "8080:8080"
    depends_on:
      - dind

volumes:
  jenkins_data:

